Repository freelancehunt/php-credit-card-validator, pull requests merged in 2021-01, with the labels that each got.

#16 Elo cards support.
  src/CreditCard.php
  tests/CreditCardTest.php
Labels: size/M

#17 Fix Elo cards detect
  src/CreditCard.php
Labels: size/S

#15 Build on php 8.0
  .travis.yml
Labels: size/XS

#18 Revert "Build on php 8.0"
  .travis.yml
Labels: size/XS

#19 Change Travis CI url
  README.md
Labels: size/XS
